run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - misspell

linters-settings:
  goimports:
    local-prefixes: github.com/hawky-4s-/k8s-ndots-admission-controller
