run:
  timeout: 5m
  tests: true

version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - misspell

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes: github.com/hawky-4s-/k8s-ndots-admission-controller
